version: '3.6'
services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - /app/node_modules
      - ./:/app
    environment:
      - HELLO=THANKU
      - PORT=3001
    ports:
      - '3001:3000'